#include "ObjectPropertiesWidget.hpp"
#include "ui_ObjectProperties.h" // The header generated from your .ui file

#include "Scene.hpp"
#include "components.hpp"
#include "QtHelpers.hpp" // Your helper functions for setting up widgets
#include "SettingsManager.hpp" // display-units (units/*) for the transform fields
#include "PrimitiveBuilders.hpp" // buildQuad / buildIcoSphere for light-type mesh swap
#include <limits>
#include <cmath>
#include <glm/gtc/quaternion.hpp> // glm::angleAxis for the emitter down-orientation

// Approximate blackbody colour (Tanner Helland fit) for a temperature in Kelvin -> RGB 0..1.
// Used by the Light tab's colour-temperature control to set lc.color.
static glm::vec3 kelvinToRgb(double kelvin)
{
    const double t = glm::clamp(kelvin, 1000.0, 40000.0) / 100.0;
    double r, g, b;
    if (t <= 66.0) { r = 255.0; }
    else           { r = 329.698727446 * std::pow(t - 60.0, -0.1332047592); }
    if (t <= 66.0) { g = 99.4708025861 * std::log(t) - 161.1195681661; }
    else           { g = 288.1221695283 * std::pow(t - 60.0, -0.0755148492); }
    if (t >= 66.0)      { b = 255.0; }
    else if (t <= 19.0) { b = 0.0; }
    else                { b = 138.5177312231 * std::log(t - 10.0) - 305.0447927307; }
    auto cl = [](double v) { return float(glm::clamp(v, 0.0, 255.0) / 255.0); };
    return glm::vec3(cl(r), cl(g), cl(b));
}

#include <QSignalBlocker>
#include <QColorDialog>
#include <QComboBox>
#include <QCheckBox>
#include <QDoubleSpinBox>
#include <QToolButton>
#include <QPushButton>
#include <QFormLayout>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QFrame>
#include <QTabWidget>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/euler_angles.hpp>

// Use the Ui namespace generated by Qt Designer
namespace Ui {
    // This is the actual class name inside the generated header
    class ObjectProperties : public Ui_Form {};
}

ObjectPropertiesWidget::ObjectPropertiesWidget(Scene* scene, QWidget* parent)
    : QWidget(parent),
    ui(new Ui::Form), // Use Ui::Form as defined in the autogen file
    m_scene(scene),
    m_currentEntity(entt::null),
    m_isUpdatingUI(false)
{
    ui->setupUi(this);    // Set up the UI defined in ObjectProperties.ui onto this widget
    initializeUI();       // Apply custom ranges, steps, and initial states
    setupConnections();   // Connect all signals from UI widgets to their corresponding slots

    setEntity(entt::null); // Initialize the panel to a blank/disabled state
}

ObjectPropertiesWidget::~ObjectPropertiesWidget()
{
    delete ui; // Clean up the UI pointer
}

// --- IMenu Interface Stubs ---

void ObjectPropertiesWidget::initializeFresh()
{
    // On a fresh start, ensure no entity is selected and the UI is clear.
    setEntity(entt::null);
}

void ObjectPropertiesWidget::initializeFromDatabase()
{
    // For now, just do a fresh initialization.
    // Later, you could load the last selected entity's ID from the database if desired.
    initializeFresh();
}

void ObjectPropertiesWidget::shutdownAndSave()
{
    // This is where you would save the state of this panel to the database if needed.
    // For an object properties panel, there's often nothing to save, as its state
    // is just a reflection of the selected object in the scene.
}

// --- Initialization ---

void ObjectPropertiesWidget::initializeUI()
{
    // Use your QtHelpers to configure spin boxes for a better user experience.
    // This makes the code cleaner and more consistent.
    WH::unbounded(ui->XPositionDoubleSpinBox);
    WH::unbounded(ui->YPositionDoubleSpinBox);
    WH::unbounded(ui->ZPositionDoubleSpinBox);
    WH::unbounded(ui->XScaleDoubleSpinBox, 3, 0.1);
    WH::unbounded(ui->YScaleDoubleSpinBox, 3, 0.1);
    WH::unbounded(ui->ZScaleDoubleSpinBox, 3, 0.1);

    WH::range180deg(ui->PitchdoubleSpinBox);
    WH::range180deg(ui->YawdoubleSpinBox);
    WH::range180deg(ui->RolldoubleSpinBox);

    WH::unbounded(ui->QuatWdoubleSpinBox, 5);
    WH::unbounded(ui->QuatXdoubleSpinBox, 5);
    WH::unbounded(ui->QuatYdoubleSpinBox, 5);
    WH::unbounded(ui->QuatZdoubleSpinBox, 5);

    // Overlay the user's display-units onto the length/angle fields (suffix,
    // decimals, range). Runs after the WH:: defaults so it wins.
    applyUnitFormatting();

    // Set initial state for stacked widgets
    ui->stackedWidget->setCurrentWidget(ui->eulerRotationStackPage);

    // Build the per-entity Light editor and add it as a tab (done in code, not the .ui).
    buildLightTab();
}

void ObjectPropertiesWidget::applyUnitFormatting()
{
    using namespace krs;
    // Length (position) fields: suffix + precision per units/length, units/lengthDecimals.
    const QString lsuf = units::lengthSuffix();
    const int     ldec = units::lengthDecimals();
    QDoubleSpinBox* pos[] = { ui->XPositionDoubleSpinBox, ui->YPositionDoubleSpinBox, ui->ZPositionDoubleSpinBox };
    for (QDoubleSpinBox* sb : pos) { sb->setDecimals(ldec); sb->setSuffix(lsuf); }

    // Angle (euler) fields: suffix + precision + range per units/angle, units/angleDecimals.
    const QString asuf = units::angleSuffix();
    const int     adec = units::angleDecimals();
    const double  alim = units::angleDisplayLimit();
    QDoubleSpinBox* eul[] = { ui->PitchdoubleSpinBox, ui->YawdoubleSpinBox, ui->RolldoubleSpinBox };
    for (QDoubleSpinBox* sb : eul) { sb->setRange(-alim, alim); sb->setDecimals(adec); sb->setSuffix(asuf); }
}

void ObjectPropertiesWidget::setupConnections()
{
    // When an item in the scene outliner is clicked, update the entire panel.
    connect(ui->sceneTreeWidget, &QTreeWidget::currentItemChanged, this, &ObjectPropertiesWidget::onSceneSelectionChanged);

    // --- Object Tab ---
    connect(ui->objectNameInputField, &QLineEdit::textChanged, this, &ObjectPropertiesWidget::onNameChanged);
    connect(ui->rotationTypeSelectionSpinBox, QOverload<int>::of(&QComboBox::currentIndexChanged), this, &ObjectPropertiesWidget::onRotationTypeChanged);

    // Connect all transform spin boxes to the same slot for efficiency
    connect(ui->XPositionDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->YPositionDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->ZPositionDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->PitchdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->YawdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->RolldoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->QuatWdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->QuatXdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->QuatYdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->QuatZdoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->XScaleDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->YScaleDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);
    connect(ui->ZScaleDoubleSpinBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onTransformChanged);

    // --- Physics Tab ---
    connect(ui->bodyTypeInputComboBox, QOverload<int>::of(&QComboBox::currentIndexChanged), this, &ObjectPropertiesWidget::onRigidBodyPropertyChanged);
    connect(ui->MassInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onRigidBodyPropertyChanged);
    connect(ui->DensityInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onRigidBodyPropertyChanged);
    connect(ui->LinearDampingInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onRigidBodyPropertyChanged);
    connect(ui->AngularDampingInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onRigidBodyPropertyChanged);

    connect(ui->SoftBodyPhysicsEnableCheckbox, &QCheckBox::toggled, this, &ObjectPropertiesWidget::onSoftBodyToggled);
    connect(ui->MaterialDampingInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onSoftBodyPropertyChanged);
    connect(ui->PressureInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onSoftBodyPropertyChanged);
    connect(ui->IntegrationTimestepInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onSoftBodyPropertyChanged);
    connect(ui->ConstraintIterationsInputSpinBox, &QSpinBox::valueChanged, this, &ObjectPropertiesWidget::onSoftBodyPropertyChanged);

    // --- Material Tab ---
    connect(ui->MaterialTreeBrowser, &QTreeWidget::itemDoubleClicked, this, &ObjectPropertiesWidget::onMaterialSelectionChanged);

    // Physical Properties
    connect(ui->YoungsModulusInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);
    connect(ui->PoissonInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);
    connect(ui->DensityInputDSBox_2, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);
    connect(ui->YieldStrengthInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);
    connect(ui->UTSInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);
    connect(ui->FatigueLimitInputDSBox, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onPhysicalPropertiesChanged);

    // Appearance Properties
    connect(ui->albedoColorPickerButton, &QToolButton::clicked, this, &ObjectPropertiesWidget::onAlbedoColorPickerClicked);
    connect(ui->EmissiveColorPickerButton, &QToolButton::clicked, this, &ObjectPropertiesWidget::onEmissiveColorPickerClicked);
    connect(ui->dispalcementTypeComboBox, QOverload<int>::of(&QComboBox::currentIndexChanged), this, &ObjectPropertiesWidget::onDisplacementTypeChanged);

    // Connect all sliders and spinboxes for appearance
    // This is verbose but ensures any change triggers an update.
    // A more advanced approach might use a QSignalMapper.
    auto connectAppearanceWidgets = [&](auto* widget) {
        connect(widget, &std::decay_t<decltype(*widget)>::valueChanged, this, &ObjectPropertiesWidget::onAppearancePropertiesChanged);
        };
    connectAppearanceWidgets(ui->albedoRInputDSBox);
    connectAppearanceWidgets(ui->albedoGInputDSBox);
    connectAppearanceWidgets(ui->albedoBInputDSBox);
    connectAppearanceWidgets(ui->textureTilingUInputDSBox);
    connectAppearanceWidgets(ui->textureTilingVInputDSBox);
    connectAppearanceWidgets(ui->opacityStrengthSlider);
    connectAppearanceWidgets(ui->metallicStrengthSlider);
    connectAppearanceWidgets(ui->roughnessStrengthSlider);
    connectAppearanceWidgets(ui->aoStrengthSlider);
    connectAppearanceWidgets(ui->normalStrengthSlider);
    connectAppearanceWidgets(ui->heightStrengthSlider);
    connectAppearanceWidgets(ui->POMStepInputDSBox);
    connectAppearanceWidgets(ui->emissiveRInputDSBox);
    connectAppearanceWidgets(ui->emissiveGInputDSBox);
    connectAppearanceWidgets(ui->emissiveBInputDSBox);
    connectAppearanceWidgets(ui->emissiveStrengthSlider);

    // --- Units hot-swap ---
    // When the user changes a display-units setting, re-apply the spin-box
    // suffix/precision/range and re-display the current selection in the new
    // units (guarded so the programmatic setValue doesn't write back).
    connect(&krs::SettingsManager::instance(), &krs::SettingsManager::changed, this,
        [this](const QString& key, const QVariant&) {
            if (!key.startsWith(QLatin1String("units/"))) return;
            applyUnitFormatting();
            if (m_scene && m_scene->getRegistry().valid(m_currentEntity)) {
                if (auto* t = m_scene->getRegistry().try_get<TransformComponent>(m_currentEntity)) {
                    const QSignalBlocker blocker(this);
                    m_isUpdatingUI = true;
                    updateTransformInputs(*t);
                    m_isUpdatingUI = false;
                }
            }
        });
}


// --- Public Slots ---

void ObjectPropertiesWidget::setEntity(entt::entity entity)
{
    const bool changed = (entity != m_currentEntity);
    m_currentEntity = entity;
    populateAllTabs();

    // When the user selects a (different) light, jump straight to the Light tab so its emitter
    // properties are immediately visible -- otherwise the "Light" tab is easy to miss among the
    // Object/Physics/Material tabs.
    if (changed && m_lightTab && ui && ui->objectPropertiesTabWidget && m_scene
        && m_scene->getRegistry().valid(entity)
        && m_scene->getRegistry().all_of<LightComponent>(entity)) {
        ui->objectPropertiesTabWidget->setCurrentWidget(m_lightTab);
    }
}


// --- Private Slots ---

void ObjectPropertiesWidget::onSceneSelectionChanged()
{
    // This slot is connected to the scene outliner's selection change signal.
    // For now, we assume you will call setEntity() directly.
    // If you connect a signal to this, you would get the entity from the QTreeWidgetItem
    // and then call setEntity().
}

void ObjectPropertiesWidget::onNameChanged(const QString& newName)
{
    if (m_isUpdatingUI) return;
    if (m_scene->getRegistry().valid(m_currentEntity))
    {
        auto& tag = m_scene->getRegistry().get_or_emplace<TagComponent>(m_currentEntity);
        tag.tag = newName.toStdString();
    }
}

void ObjectPropertiesWidget::onTransformChanged()
{
    if (m_isUpdatingUI) return;
    updateTransformComponent();
}

void ObjectPropertiesWidget::onRotationTypeChanged(int index)
{
    if (m_isUpdatingUI) return;
    ui->stackedWidget->setCurrentIndex(index);
    // When switching, re-read the component to ensure the displayed values are correct
    if (m_scene->getRegistry().valid(m_currentEntity)) {
        if (auto* transform = m_scene->getRegistry().try_get<TransformComponent>(m_currentEntity)) {
            const QSignalBlocker blocker(this);
            m_isUpdatingUI = true;
            // Re-populate the transform inputs to sync both Euler and Quat fields
            updateTransformInputs(*transform);
            m_isUpdatingUI = false;
        }
    }
}

void ObjectPropertiesWidget::onRigidBodyPropertyChanged()
{
    if (m_isUpdatingUI) return;
    updateRigidBodyComponent();
    // C3: live-apply the change (esp. bodyType) so it does NOT wait for a stop()/play() that
    // would restore the authored pose. MainWindow forwards this to notifyEntityChanged.
    if (m_scene && m_scene->getRegistry().valid(m_currentEntity))
        emit entityComponentsChanged(m_currentEntity);
}

void ObjectPropertiesWidget::onSoftBodyToggled(bool checked)
{
    if (m_isUpdatingUI) return;
    ui->groupBox_7->setEnabled(checked); // FEM Properties
    ui->groupBox_11->setEnabled(checked); // Solver Settings

    if (m_scene->getRegistry().valid(m_currentEntity)) {
        if (checked) {
            m_scene->getRegistry().get_or_emplace<SoftBodyComponent>(m_currentEntity);
        }
        else {
            m_scene->getRegistry().remove<SoftBodyComponent>(m_currentEntity);
        }
    }
}

void ObjectPropertiesWidget::onSoftBodyPropertyChanged()
{
    if (m_isUpdatingUI) return;
    updateSoftBodyComponent();
}

void ObjectPropertiesWidget::onMaterialSelectionChanged()
{
    // Logic to load a .KMaterial file and apply it to the entity would go here.
    // For now, this is a placeholder.
    qDebug() << "Material selection changed (not yet implemented).";
}

void ObjectPropertiesWidget::onPhysicalPropertiesChanged()
{
    if (m_isUpdatingUI) return;
    updateMaterialComponent();
    updateDerivedMechanicalProperties();
}

void ObjectPropertiesWidget::onAppearancePropertiesChanged()
{
    if (m_isUpdatingUI) return;
    updateMaterialComponent();
}

void ObjectPropertiesWidget::onAlbedoColorPickerClicked()
{
    if (m_isUpdatingUI) return;
    QColor newColor = QColorDialog::getColor(Qt::white, this, "Select Albedo Color");
    if (newColor.isValid()) {
        glm::vec3 color = { newColor.redF(), newColor.greenF(), newColor.blueF() };
        setUIColor(color, ui->albedoColorPreviewFrame, ui->albedoRInputDSBox, ui->albedoGInputDSBox, ui->albedoBInputDSBox);
        onAppearancePropertiesChanged(); // Trigger update
    }
}

void ObjectPropertiesWidget::onEmissiveColorPickerClicked()
{
    if (m_isUpdatingUI) return;
    QColor newColor = QColorDialog::getColor(Qt::black, this, "Select Emissive Color");
    if (newColor.isValid()) {
        glm::vec3 color = { newColor.redF(), newColor.greenF(), newColor.blueF() };
        setUIColor(color, ui->emissiveColorPreviewFrame, ui->emissiveRInputDSBox, ui->emissiveGInputDSBox, ui->emissiveBInputDSBox);
        onAppearancePropertiesChanged(); // Trigger update
    }
}

void ObjectPropertiesWidget::onDisplacementTypeChanged(int index)
{
    if (m_isUpdatingUI) return;
    if (!m_scene->getRegistry().valid(m_currentEntity)) return;

    auto& registry = m_scene->getRegistry();
    // 0 = POM, 1 = Tessellation, 2 = None
    ui->POMStepInputDSBox->setEnabled(index == 0);

    registry.remove<ParallaxMaterialTag>(m_currentEntity);
    registry.remove<TessellatedMaterialTag>(m_currentEntity);

    if (index == 0) {
        registry.emplace<ParallaxMaterialTag>(m_currentEntity);
    }
    else if (index == 1) {
        registry.emplace<TessellatedMaterialTag>(m_currentEntity);
    }
    updateMaterialComponent();
}


// --- UI Population and Update Logic ---

void ObjectPropertiesWidget::populateAllTabs()
{
    const QSignalBlocker blocker(this);
    m_isUpdatingUI = true;

    bool isValid = m_scene->getRegistry().valid(m_currentEntity);
    this->setEnabled(isValid);

    if (isValid) {
        populateObjectTab();
        populatePhysicsTab();
        populateMaterialTab();
    }
    else {
        // Clear all fields if no entity is selected
        ui->objectNameInputField->clear();
        ui->XPositionDoubleSpinBox->setValue(0);
        // ... clear all other inputs ...
    }

    populateLightTab();   // handles both valid (Add button / editor) and invalid (hidden)
    m_isUpdatingUI = false;
}

void ObjectPropertiesWidget::populateObjectTab()
{
    if (auto* tag = m_scene->getRegistry().try_get<TagComponent>(m_currentEntity)) {
        ui->objectNameInputField->setText(QString::fromStdString(tag->tag));
    }
    else {
        ui->objectNameInputField->setText("");
    }

    if (auto* transform = m_scene->getRegistry().try_get<TransformComponent>(m_currentEntity)) {
        updateTransformInputs(*transform);
    }
}

void ObjectPropertiesWidget::populatePhysicsTab()
{
    // Rigid Body
    if (auto* rb = m_scene->getRegistry().try_get<RigidBodyComponent>(m_currentEntity)) {
        ui->bodyTypeInputComboBox->setCurrentIndex(static_cast<int>(rb->bodyType));
        ui->MassInputDSBox->setValue(rb->mass);
        ui->LinearDampingInputDSBox->setValue(rb->linearDamping);
        ui->AngularDampingInputDSBox->setValue(rb->angularDamping);
    }

    // Soft Body
    bool hasSoftBody = m_scene->getRegistry().all_of<SoftBodyComponent>(m_currentEntity);
    ui->SoftBodyPhysicsEnableCheckbox->setChecked(hasSoftBody);
    ui->groupBox_7->setEnabled(hasSoftBody);
    ui->groupBox_11->setEnabled(hasSoftBody);

    if (hasSoftBody) {
        // Populate soft body fields
    }
}

void ObjectPropertiesWidget::populateMaterialTab()
{
    // This is a simplified version. A full implementation would involve
    // loading the material from the entity's MaterialComponent.
    if (auto* mat = m_scene->getRegistry().try_get<MaterialComponent>(m_currentEntity)) {
        // Populate Physical Properties
        ui->YoungsModulusInputDSBox->setValue(0); // Placeholder
        // ... populate other physical properties ...

        updateDerivedMechanicalProperties();

        // Populate Appearance Properties
        populateAppearanceTab(*mat);
    }
}

void ObjectPropertiesWidget::populateAppearanceTab(const MaterialComponent& mat)
{
    // Albedo
    setUIColor(mat.albedoColor, ui->albedoColorPreviewFrame, ui->albedoRInputDSBox, ui->albedoGInputDSBox, ui->albedoBInputDSBox);
    ui->textureTilingUInputDSBox->setValue(mat.albedoTiling.x);
    ui->textureTilingVInputDSBox->setValue(mat.albedoTiling.y);

    // Opacity, Metallic, Roughness, AO, Normal, Height
    ui->opacityStrengthSlider->setValue(mat.opacity * 1000);
    ui->metallicStrengthSlider->setValue(mat.metallic * 1000);
    ui->roughnessStrengthSlider->setValue(mat.roughness * 1000);
    ui->aoStrengthSlider->setValue(mat.ao * 1000);
    ui->normalStrengthSlider->setValue(mat.normalScale * 100);
    ui->heightStrengthSlider->setValue(mat.heightScale * 100);

    // Displacement
    if (m_scene->getRegistry().all_of<ParallaxMaterialTag>(m_currentEntity)) {
        ui->dispalcementTypeComboBox->setCurrentIndex(0);
    }
    else if (m_scene->getRegistry().all_of<TessellatedMaterialTag>(m_currentEntity)) {
        ui->dispalcementTypeComboBox->setCurrentIndex(1);
    }
    else {
        ui->dispalcementTypeComboBox->setCurrentIndex(2);
    }
    ui->POMStepInputDSBox->setValue(mat.parallaxSteps);

    // Emissive
    setUIColor(mat.emissiveColor, ui->emissiveColorPreviewFrame, ui->emissiveRInputDSBox, ui->emissiveGInputDSBox, ui->emissiveBInputDSBox);
    ui->emissiveStrengthSlider->setValue(mat.emissiveStrength * 100);
}

void ObjectPropertiesWidget::updateDerivedMechanicalProperties()
{
    // Read inputs, calculate derived values, and set read-only labels.
    // This is a placeholder for the actual physics calculations.
    ui->ShearModulusLabel->setText("N/A");
    ui->BulkModulusLabel->setText("N/A");
    ui->ResilienceModLabel->setText("N/A");
    ui->LameParamLabel->setText("N/A");
}

void ObjectPropertiesWidget::updateTransformInputs(const TransformComponent& transform)
{
    // Storage is metres/radians; show in the user's display units (units/*).
    ui->XPositionDoubleSpinBox->setValue(krs::units::metersToDisplay(transform.translation.x));
    ui->YPositionDoubleSpinBox->setValue(krs::units::metersToDisplay(transform.translation.y));
    ui->ZPositionDoubleSpinBox->setValue(krs::units::metersToDisplay(transform.translation.z));

    glm::vec3 eulerRadians = glm::eulerAngles(transform.rotation);
    ui->PitchdoubleSpinBox->setValue(krs::units::radiansToDisplay(eulerRadians.x));
    ui->YawdoubleSpinBox->setValue(krs::units::radiansToDisplay(eulerRadians.y));
    ui->RolldoubleSpinBox->setValue(krs::units::radiansToDisplay(eulerRadians.z));

    ui->QuatWdoubleSpinBox->setValue(transform.rotation.w);
    ui->QuatXdoubleSpinBox->setValue(transform.rotation.x);
    ui->QuatYdoubleSpinBox->setValue(transform.rotation.y);
    ui->QuatZdoubleSpinBox->setValue(transform.rotation.z);

    ui->XScaleDoubleSpinBox->setValue(transform.scale.x);
    ui->YScaleDoubleSpinBox->setValue(transform.scale.y);
    ui->ZScaleDoubleSpinBox->setValue(transform.scale.z);
}


void ObjectPropertiesWidget::updateTransformComponent()
{
    if (!m_scene->getRegistry().valid(m_currentEntity)) return;
    auto& transform = m_scene->getRegistry().get<TransformComponent>(m_currentEntity);

    // Spin boxes are in display units; convert back to canonical metres/radians.
    transform.translation = {
        float(krs::units::displayToMeters(ui->XPositionDoubleSpinBox->value())),
        float(krs::units::displayToMeters(ui->YPositionDoubleSpinBox->value())),
        float(krs::units::displayToMeters(ui->ZPositionDoubleSpinBox->value()))
    };

    if (ui->rotationTypeSelectionSpinBox->currentIndex() == 0) { // Euler
        glm::vec3 eulerRadians(
            float(krs::units::displayToRadians(ui->PitchdoubleSpinBox->value())),
            float(krs::units::displayToRadians(ui->YawdoubleSpinBox->value())),
            float(krs::units::displayToRadians(ui->RolldoubleSpinBox->value())));
        transform.rotation = glm::quat(eulerRadians);
    }
    else { // Quaternion
        transform.rotation = glm::normalize(glm::quat(
            ui->QuatWdoubleSpinBox->value(),
            ui->QuatXdoubleSpinBox->value(),
            ui->QuatYdoubleSpinBox->value(),
            ui->QuatZdoubleSpinBox->value()
        ));
    }

    transform.scale = {
        ui->XScaleDoubleSpinBox->value(),
        ui->YScaleDoubleSpinBox->value(),
        ui->ZScaleDoubleSpinBox->value()
    };
}

void ObjectPropertiesWidget::updateRigidBodyComponent()
{
    if (!m_scene->getRegistry().valid(m_currentEntity)) return;
    auto& rb = m_scene->getRegistry().get_or_emplace<RigidBodyComponent>(m_currentEntity);

    rb.bodyType = static_cast<RigidBodyComponent::BodyType>(ui->bodyTypeInputComboBox->currentIndex());
    rb.mass = ui->MassInputDSBox->value();
    // Add logic to link mass and density here
    rb.linearDamping = ui->LinearDampingInputDSBox->value();
    rb.angularDamping = ui->AngularDampingInputDSBox->value();
}

void ObjectPropertiesWidget::updateSoftBodyComponent()
{
    if (!m_scene->getRegistry().valid(m_currentEntity)) return;
    if (!m_scene->getRegistry().all_of<SoftBodyComponent>(m_currentEntity)) return;

    // auto& sb = m_scene->getRegistry().get<SoftBodyComponent>(m_currentEntity);
    // Update soft body properties here
}

void ObjectPropertiesWidget::updateMaterialComponent()
{
    if (!m_scene->getRegistry().valid(m_currentEntity)) return;
    auto& mat = m_scene->getRegistry().get_or_emplace<MaterialComponent>(m_currentEntity);

    // Update all material properties from the UI
    mat.albedoColor.r = ui->albedoRInputDSBox->value() / 255.0f;
    mat.albedoColor.g = ui->albedoGInputDSBox->value() / 255.0f;
    mat.albedoColor.b = ui->albedoBInputDSBox->value() / 255.0f;

    mat.albedoTiling.x = ui->textureTilingUInputDSBox->value();
    mat.albedoTiling.y = ui->textureTilingVInputDSBox->value();

    mat.opacity = ui->opacityStrengthSlider->value() / 1000.0f;
    mat.metallic = ui->metallicStrengthSlider->value() / 1000.0f;
    mat.roughness = ui->roughnessStrengthSlider->value() / 1000.0f;
    mat.ao = ui->aoStrengthSlider->value() / 1000.0f;
    mat.normalScale = ui->normalStrengthSlider->value() / 100.0f;
    mat.heightScale = ui->heightStrengthSlider->value() / 100.0f;

    mat.parallaxSteps = ui->POMStepInputDSBox->value();

    mat.emissiveColor.r = ui->emissiveRInputDSBox->value() / 255.0f;
    mat.emissiveColor.g = ui->emissiveGInputDSBox->value() / 255.0f;
    mat.emissiveColor.b = ui->emissiveBInputDSBox->value() / 255.0f;
    mat.emissiveStrength = ui->emissiveStrengthSlider->value() / 100.0f;
}

void ObjectPropertiesWidget::setUIColor(const glm::vec3& color, QFrame* frame, QSpinBox* r, QSpinBox* g, QSpinBox* b)
{
    QColor qColor;
    qColor.setRgbF(color.r, color.g, color.b);
    frame->setStyleSheet(QString("background-color: %1;").arg(qColor.name()));
    r->setValue(qColor.red());
    g->setValue(qColor.green());
    b->setValue(qColor.blue());
}

// ============================== LIGHT TAB ==============================
// A per-entity Light editor, built in code and added as a tab to the existing
// objectPropertiesTabWidget. When the selected entity is not a light it shows a single
// "Add Light Emitter" button (turn ANY body into an emitter); otherwise it edits the
// entity's LightComponent and keeps the emissive glow + RectArea quad in sync.

void ObjectPropertiesWidget::buildLightTab()
{
    m_lightTab = new QWidget(this);
    auto* outer = new QVBoxLayout(m_lightTab);
    outer->setContentsMargins(8, 8, 8, 8);

    // Shown when the entity has NO LightComponent: one-click "make this body a light".
    m_addLightBtn = new QPushButton(QStringLiteral("Add Light Emitter to this Object"), m_lightTab);
    outer->addWidget(m_addLightBtn);
    connect(m_addLightBtn, &QPushButton::clicked, this, &ObjectPropertiesWidget::onAddLightEmitterClicked);

    // The editor (shown when the entity IS a light).
    m_lightControls = new QWidget(m_lightTab);
    m_lightForm = new QFormLayout(m_lightControls);
    m_lightForm->setLabelAlignment(Qt::AlignRight);

    m_lightTypeCombo = new QComboBox(m_lightControls);
    m_lightTypeCombo->addItems({ QStringLiteral("Point"), QStringLiteral("Directional"),
                                 QStringLiteral("Spot"),  QStringLiteral("Rect Area") });
    m_lightForm->addRow(QStringLiteral("Type"), m_lightTypeCombo);

    m_lightEnabled = new QCheckBox(QStringLiteral("Light on"), m_lightControls);
    m_lightForm->addRow(QStringLiteral("Enabled"), m_lightEnabled);

    // Colour: pick button + swatch preview.
    {
        auto* row = new QWidget(m_lightControls);
        auto* h = new QHBoxLayout(row);
        h->setContentsMargins(0, 0, 0, 0);
        m_lightColorBtn = new QToolButton(row);
        m_lightColorBtn->setText(QStringLiteral("Pick…"));
        m_lightColorSwatch = new QFrame(row);
        m_lightColorSwatch->setMinimumSize(40, 18);
        m_lightColorSwatch->setFrameShape(QFrame::StyledPanel);
        h->addWidget(m_lightColorBtn);
        h->addWidget(m_lightColorSwatch, 1);
        m_lightForm->addRow(QStringLiteral("Colour"), row);
        connect(m_lightColorBtn, &QToolButton::clicked, this, &ObjectPropertiesWidget::onLightColorPickerClicked);
    }

    // Colour temperature (blackbody): a convenience that sets the colour from Kelvin.
    m_lightKelvin = new QDoubleSpinBox(m_lightControls);
    m_lightKelvin->setRange(1500.0, 12000.0);
    m_lightKelvin->setSingleStep(100.0);
    m_lightKelvin->setDecimals(0);
    m_lightKelvin->setValue(6500.0);
    m_lightKelvin->setToolTip(QStringLiteral("Set the colour from a blackbody temperature: 2700K warm, 6500K daylight, 10000K cool."));
    m_lightForm->addRow(QStringLiteral("Temperature (K)"), m_lightKelvin);

    auto makeSpin = [&](double mn, double mx, double step, int dec) {
        auto* s = new QDoubleSpinBox(m_lightControls);
        s->setRange(mn, mx); s->setSingleStep(step); s->setDecimals(dec);
        return s;
    };
    // Intensity range is wide: lumens (point) can reach 10^6; the row label shows the unit per type.
    m_lightIntensity = makeSpin(0.0, 2000000.0, 100.0, 1);
    m_lightForm->addRow(QStringLiteral("Intensity"), m_lightIntensity);
    m_lightRange = makeSpin(0.0, 1000.0, 0.1, 2);
    m_lightForm->addRow(QStringLiteral("Range (m)"), m_lightRange);
    m_lightInner = makeSpin(0.0, 89.0, 1.0, 1);
    m_lightForm->addRow(QStringLiteral("Inner cone (deg)"), m_lightInner);
    m_lightOuter = makeSpin(0.0, 90.0, 1.0, 1);
    m_lightForm->addRow(QStringLiteral("Outer cone (deg)"), m_lightOuter);
    m_lightSizeX = makeSpin(0.01, 1000.0, 0.1, 2);
    m_lightForm->addRow(QStringLiteral("Width (m)"), m_lightSizeX);
    m_lightSizeY = makeSpin(0.01, 1000.0, 0.1, 2);
    m_lightForm->addRow(QStringLiteral("Height (m)"), m_lightSizeY);
    m_lightTwoSided = new QCheckBox(QStringLiteral("Emit from both faces"), m_lightControls);
    m_lightForm->addRow(QStringLiteral("Two-sided"), m_lightTwoSided);

    m_removeLightBtn = new QPushButton(QStringLiteral("Remove Light Emitter"), m_lightControls);
    m_lightForm->addRow(QString(), m_removeLightBtn);

    outer->addWidget(m_lightControls);
    outer->addStretch(1);

    connect(m_lightTypeCombo, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &ObjectPropertiesWidget::onLightTypeChanged);
    connect(m_lightEnabled,  &QCheckBox::toggled, this, &ObjectPropertiesWidget::onLightPropertyChanged);
    connect(m_lightTwoSided, &QCheckBox::toggled, this, &ObjectPropertiesWidget::onLightPropertyChanged);
    for (QDoubleSpinBox* s : { m_lightIntensity, m_lightRange, m_lightInner, m_lightOuter })
        connect(s, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onLightPropertyChanged);
    // Width/Height drive the transform's XY scale on a SEPARATE path, so editing colour/
    // intensity/etc. never rewrites (and resets) a gizmo- or field-set scale.
    connect(m_lightSizeX, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onLightSizeChanged);
    connect(m_lightSizeY, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onLightSizeChanged);
    connect(m_lightKelvin, &QDoubleSpinBox::valueChanged, this, &ObjectPropertiesWidget::onLightKelvinChanged);
    connect(m_removeLightBtn, &QPushButton::clicked, this, &ObjectPropertiesWidget::onRemoveLightEmitterClicked);

    ui->objectPropertiesTabWidget->addTab(m_lightTab, QStringLiteral("Light"));
}

void ObjectPropertiesWidget::updateLightColorPreview()
{
    if (!m_lightColorSwatch) return;
    QColor c;
    c.setRgbF(glm::clamp(m_lightColor.r, 0.0f, 1.0f),
              glm::clamp(m_lightColor.g, 0.0f, 1.0f),
              glm::clamp(m_lightColor.b, 0.0f, 1.0f));
    m_lightColorSwatch->setStyleSheet(QString("background-color: %1;").arg(c.name()));
}

void ObjectPropertiesWidget::updateLightFieldVisibility(int type)
{
    using T = LightComponent::Type;
    const T t = static_cast<T>(type);
    const bool isPoint = (t == T::Point);
    const bool isSpot  = (t == T::Spot);
    const bool isRect  = (t == T::RectArea);
    // Show only the rows that matter for this light type (label + field together).
    auto setRow = [&](QWidget* field, bool vis) {
        if (!field) return;
        field->setVisible(vis);
        if (QWidget* lbl = m_lightForm->labelForField(field)) lbl->setVisible(vis);
    };
    setRow(m_lightRange,    isPoint || isSpot);
    setRow(m_lightInner,    isSpot);
    setRow(m_lightOuter,    isSpot);
    setRow(m_lightSizeX,    isRect);
    setRow(m_lightSizeY,    isRect);
    setRow(m_lightTwoSided, isRect);
    // The intensity unit depends on the light type (photometric).
    if (auto* il = qobject_cast<QLabel*>(m_lightForm->labelForField(m_lightIntensity))) {
        il->setText(isRect ? QStringLiteral("Luminance [nits]")
                  : isSpot ? QStringLiteral("Intensity [cd]")
                  : (t == T::Directional) ? QStringLiteral("Illuminance [lux]")
                                          : QStringLiteral("Power [lm]"));
    }
}

void ObjectPropertiesWidget::populateLightTab()
{
    if (!m_lightTab) return;
    auto& reg = m_scene->getRegistry();
    const bool valid = reg.valid(m_currentEntity);
    LightComponent* lc = valid ? reg.try_get<LightComponent>(m_currentEntity) : nullptr;

    m_addLightBtn->setVisible(valid && lc == nullptr);
    m_lightControls->setVisible(lc != nullptr);
    if (!lc) return;

    m_lightTypeCombo->setCurrentIndex(static_cast<int>(lc->type));
    m_lightEnabled->setChecked(lc->enabled);
    m_lightColor = lc->color;
    updateLightColorPreview();
    m_lightIntensity->setValue(lc->intensity);
    m_lightRange->setValue(lc->range);
    m_lightInner->setValue(lc->innerConeDeg);
    m_lightOuter->setValue(lc->outerConeDeg);
    // Width/Height reflect the LIVE transform scale (so gizmo-scaling shows here and a later
    // colour edit can't reset it); fall back to lc.size if the entity has no transform.
    if (auto* xf = reg.try_get<TransformComponent>(m_currentEntity)) {
        m_lightSizeX->setValue(xf->scale.x);
        m_lightSizeY->setValue(xf->scale.y);
    } else {
        m_lightSizeX->setValue(lc->size.x);
        m_lightSizeY->setValue(lc->size.y);
    }
    m_lightTwoSided->setChecked(lc->twoSided);
    updateLightFieldVisibility(static_cast<int>(lc->type));
}

void ObjectPropertiesWidget::updateLightComponent()
{
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    auto& lc = reg.get_or_emplace<LightComponent>(m_currentEntity);
    lc.type        = static_cast<LightComponent::Type>(m_lightTypeCombo->currentIndex());
    lc.enabled     = m_lightEnabled->isChecked();
    lc.color       = m_lightColor;
    lc.intensity   = static_cast<float>(m_lightIntensity->value());
    lc.range       = static_cast<float>(m_lightRange->value());
    lc.innerConeDeg= static_cast<float>(m_lightInner->value());
    lc.outerConeDeg= static_cast<float>(m_lightOuter->value());
    lc.twoSided    = m_lightTwoSided->isChecked();
    // NOTE: deliberately does NOT touch lc.size or the transform scale -- the RectArea size is
    // owned by the transform (gizmo) + onLightSizeChanged, so colour/intensity edits preserve it.

    // Keep the glowing bulb colour in sync with the emitted colour (lighting pass x10).
    auto& mat = reg.get_or_emplace<MaterialComponent>(m_currentEntity);
    mat.emissiveColor = lc.color;

    emit entityComponentsChanged(m_currentEntity);
}

void ObjectPropertiesWidget::onLightSizeChanged()
{
    if (m_isUpdatingUI) return;
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    // The RectArea world size IS the transform's XY scale (LightingPass builds the LTC corners
    // from the unit quad * transform). Only this handler writes it.
    if (auto* xf = reg.try_get<TransformComponent>(m_currentEntity)) {
        xf->scale.x = static_cast<float>(m_lightSizeX->value());
        xf->scale.y = static_cast<float>(m_lightSizeY->value());
    }
    if (auto* lc = reg.try_get<LightComponent>(m_currentEntity))
        lc->size = glm::vec2(float(m_lightSizeX->value()), float(m_lightSizeY->value()));
    emit entityComponentsChanged(m_currentEntity);
}

void ObjectPropertiesWidget::onLightTypeChanged(int)
{
    if (m_isUpdatingUI) return;
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    const int t = m_lightTypeCombo->currentIndex();
    // Set the new type, then (for dedicated light primitives only) swap the visible mesh +
    // reset scale/orientation. Re-read the whole panel because size/scale may have changed.
    reg.get_or_emplace<LightComponent>(m_currentEntity).type = static_cast<LightComponent::Type>(t);
    rebuildEmitterMeshForType(m_currentEntity, t);
    populateAllTabs();
    emit entityComponentsChanged(m_currentEntity);
}

void ObjectPropertiesWidget::rebuildEmitterMeshForType(entt::entity e, int type)
{
    auto& reg = m_scene->getRegistry();
    // ONLY dedicated light primitives (spawned bulbs/panels) get their mesh swapped. A body
    // the user merely turned into a light (no LightEmitterTag) keeps its own geometry.
    if (!reg.valid(e) || !reg.all_of<LightEmitterTag>(e)) return;
    auto* meshC = reg.try_get<RenderableMeshComponent>(e);
    if (!meshC) return;

    using T = LightComponent::Type;
    const T t = static_cast<T>(type);
    std::vector<uint32_t> idx;
    if (t == T::RectArea) buildQuad(meshC->vertices, idx);
    else                  buildIcoSphere(meshC->vertices, idx, 2);
    meshC->indices.assign(idx.begin(), idx.end());
    meshC->hasUVs = false;
    meshC->hasTangents = false;

    glm::vec3 mn(std::numeric_limits<float>::max());
    glm::vec3 mx(std::numeric_limits<float>::lowest());
    for (const auto& v : meshC->vertices) { mn = glm::min(mn, v.position); mx = glm::max(mx, v.position); }
    meshC->aabbMin = mn;
    meshC->aabbMax = mx;

    if (auto* xf = reg.try_get<TransformComponent>(e)) {
        if (t == T::RectArea) {
            xf->scale = glm::vec3(2.0f, 2.0f, 1.0f);
            xf->rotation = glm::angleAxis(glm::radians(90.0f), glm::vec3(1.0f, 0.0f, 0.0f)); // face down
            reg.get_or_emplace<LightComponent>(e).size = glm::vec2(2.0f, 2.0f); // size mirrors scale
        } else {
            xf->scale = glm::vec3(0.15f);
            if (t == T::Spot || t == T::Directional)
                xf->rotation = glm::angleAxis(glm::radians(90.0f), glm::vec3(1.0f, 0.0f, 0.0f));
        }
    }
    // Force the GPU buffers to be rebuilt from the new vertex data next frame.
    reg.remove<RenderResourceComponent>(e);
}

void ObjectPropertiesWidget::onLightPropertyChanged()
{
    if (m_isUpdatingUI) return;
    updateLightComponent();
}

void ObjectPropertiesWidget::onLightColorPickerClicked()
{
    if (m_isUpdatingUI) return;
    QColor init;
    init.setRgbF(glm::clamp(m_lightColor.r, 0.0f, 1.0f),
                 glm::clamp(m_lightColor.g, 0.0f, 1.0f),
                 glm::clamp(m_lightColor.b, 0.0f, 1.0f));
    const QColor c = QColorDialog::getColor(init, this, QStringLiteral("Select Light Colour"));
    if (!c.isValid()) return;
    m_lightColor = glm::vec3(float(c.redF()), float(c.greenF()), float(c.blueF()));
    updateLightColorPreview();
    updateLightComponent();
}

void ObjectPropertiesWidget::selfTestSelectLightTab()
{
    if (m_lightTab && ui && ui->objectPropertiesTabWidget)
        ui->objectPropertiesTabWidget->setCurrentWidget(m_lightTab);
}

void ObjectPropertiesWidget::selfTestNudgeLight()
{
    // Drive the REAL controls (NOT under the m_isUpdatingUI guard) so the same slots a user
    // interaction fires run end-to-end: spinbox valueChanged -> updateLightComponent ->
    // registry -> next frame renders. A before/after grab then pixel-proves the hot-update.
    if (m_lightTab && ui && ui->objectPropertiesTabWidget)
        ui->objectPropertiesTabWidget->setCurrentWidget(m_lightTab);
    if (m_lightKelvin)    m_lightKelvin->setValue(2000.0);   // -> deep orange via onLightKelvinChanged
    if (m_lightIntensity) m_lightIntensity->setValue(m_lightIntensity->value() * 6.0 + 80000.0);
}

void ObjectPropertiesWidget::selfTestAddAndGlowEmitter()
{
    onAddLightEmitterClicked();   // the real "Add Light Emitter to this Object" path
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    if (auto* mat = reg.try_get<MaterialComponent>(m_currentEntity)) {
        mat->emissiveColor    = glm::vec3(0.0f, 1.0f, 1.0f);  // obvious cyan glow on the textured surface
        mat->emissiveStrength = 8.0f;
    }
    emit entityComponentsChanged(m_currentEntity);
}

void ObjectPropertiesWidget::onLightKelvinChanged(double kelvin)
{
    if (m_isUpdatingUI) return;
    m_lightColor = kelvinToRgb(kelvin);
    updateLightColorPreview();
    updateLightComponent();
}

void ObjectPropertiesWidget::onAddLightEmitterClicked()
{
    if (m_isUpdatingUI) return;
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    // Capture the body's CURRENT emissive so removing the light can restore it.
    LightEmitterPrevEmissive prev;
    if (auto* m = reg.try_get<MaterialComponent>(m_currentEntity)) { prev.color = m->emissiveColor; prev.strength = m->emissiveStrength; }
    reg.emplace_or_replace<LightEmitterPrevEmissive>(m_currentEntity, prev);

    auto& lc     = reg.get_or_emplace<LightComponent>(m_currentEntity);
    lc.type      = LightComponent::Type::Point;
    lc.color     = glm::vec3(1.0f, 0.95f, 0.88f);
    lc.intensity = 60.0f;
    lc.enabled   = true;
    // Glow the body in its light colour. NOTE: deliberately NOT adding LightEmitterTag -- this
    // is an existing body, not a dedicated light primitive, so its mesh must never be swapped
    // when the type changes.
    auto& mat = reg.get_or_emplace<MaterialComponent>(m_currentEntity);
    mat.emissiveColor = lc.color;
    if (mat.emissiveStrength <= 0.0f) mat.emissiveStrength = 4.0f;
    emit entityComponentsChanged(m_currentEntity);
    populateAllTabs();   // re-read: the editor replaces the Add button
}

void ObjectPropertiesWidget::onRemoveLightEmitterClicked()
{
    if (m_isUpdatingUI) return;
    auto& reg = m_scene->getRegistry();
    if (!reg.valid(m_currentEntity)) return;
    reg.remove<LightComponent>(m_currentEntity);
    reg.remove<LightEmitterTag>(m_currentEntity);
    // Restore the emissive the body had BEFORE it became an emitter (don't wipe authored or
    // simulation-driven glow). Leave the material untouched if we never captured one.
    if (auto* prev = reg.try_get<LightEmitterPrevEmissive>(m_currentEntity)) {
        if (auto* mat = reg.try_get<MaterialComponent>(m_currentEntity)) {
            mat->emissiveColor    = prev->color;
            mat->emissiveStrength = prev->strength;
        }
        reg.remove<LightEmitterPrevEmissive>(m_currentEntity);
    }
    emit entityComponentsChanged(m_currentEntity);
    populateAllTabs();
}
