#pragma once

#include <QObject>
#include <QString>
#include <QStringList>
#include <QVariant>
#include <QVariantList>
#include <QColor>
#include <QSettings>
#include <vector>
#include <glm/glm.hpp>

namespace krs {

// One row of the settings registry: the single source of truth for a setting's
// identity, type, default, range and UI metadata. The Settings dialog is
// generated by iterating these, and the self-test validates against them.
struct SettingDef {
    enum Type { Bool, Int, Float, Enum, Color, Vec3, String };

    QString      key;          // e.g. "render/iblIntensity" (also the QSettings key)
    QString      label;        // human label for the UI
    QString      category;     // UI tab/section
    Type         type = Float;
    QVariant     defaultValue; // mirrors the current hardcoded behaviour
    double       min = 0.0;
    double       max = 1.0;
    double       step = 0.1;
    int          decimals = 3; // for Float editors
    QStringList  enumLabels;   // Enum: display labels
    QVariantList enumValues;   // Enum: stored values (parallel to enumLabels)
    QString      note;         // optional UI badge, e.g. "applies after restart"
};

// Central, persistent (QSettings) settings store. Knows nothing about the
// renderer/physics; it only stores values and emits changed() so the owner
// (MainWindow) can route each key to its subsystem applier for hot-swap.
class SettingsManager : public QObject {
    Q_OBJECT
public:
    static SettingsManager& instance();

    const std::vector<SettingDef>& registry() const { return m_defs; }
    const SettingDef*              def(const QString& key) const;
    QStringList                    categories() const;     // in registry order

    // Persisted value (falls back to the registry default), clamped to range.
    QVariant value(const QString& key) const;
    // Persist + emit changed(). No-op if unchanged.
    void     set(const QString& key, const QVariant& v);

    void resetKey(const QString& key);
    void resetCategory(const QString& category);
    void resetAll();

    // Typed convenience accessors.
    float     getFloat(const QString& key) const;
    int       getInt(const QString& key) const;
    bool      getBool(const QString& key) const;
    QString   getString(const QString& key) const;
    QColor    getColor(const QString& key) const;
    glm::vec3 getVec3(const QString& key) const;        // stored as "x,y,z"
    glm::vec3 getColorVec3(const QString& key) const;   // QColor -> linear-ish rgb 0..1

    // Helpers for the vec3/color serialization used in the registry/dialog.
    static QString   vec3ToString(const glm::vec3& v);
    static glm::vec3 vec3FromVariant(const QVariant& v);

    // Test / CLI helpers.
    void       setFromString(const QString& key, const QString& valueStr); // type-aware parse
    static int selfTest(); // headless round-trip/persistence/clamp/default gate; returns #failures (0 = pass)

signals:
    void changed(const QString& key, const QVariant& value);

private:
    SettingsManager();
    void     buildRegistry();
    QVariant clampToDef(const SettingDef& d, const QVariant& v) const;

    std::vector<SettingDef> m_defs;
    mutable QSettings       m_settings; // resolves to org/app set in main.cpp
};

} // namespace krs
