#pragma once

#include <QWidget>
#include <QPointer>

#include "Node.hpp"
#include "NodeFactory.hpp"
#include <glm/glm.hpp>
#include <string>
#include <vector>
#include <functional>
#include <deque>

class QLCDNumber;   // Qt's built-in 7-segment display (used by the numeric readout)

namespace NodeLibrary {

    // --- Data Structures ---

    /** @brief A single rule for the ConditionalLightNode. */
    struct LightCondition {
        // A function that takes the input and returns true if the condition is met.
        std::function<bool(float)> condition;
        glm::vec4 color;
    };

    /** @brief A log entry generated by a DataMonitorNode. */
    struct ErrorLogEntry {
        double timestamp;
        std::string sourceNodeID;
        std::string message;
        enum class Severity { Info, Warning, Error, Critical } severity;
        // In a real system, this would also contain a snapshot of dependencies.
    };


    // --- Visualization Nodes ---

    /**
     * @brief A configurable "stoplight" that changes color based on input.
     * The actual rendering of the light is handled by the IDE's UI.
     */
    class ConditionalLightNode : public Node {
    public:
        QWidget* createCustomWidget() override;
        // This vector of rules would be configured in the IDE's property editor.
        std::vector<LightCondition> conditions;
        glm::vec4 defaultColor = { 0.2f, 0.2f, 0.2f, 1.0f }; // Default gray/off color

        ConditionalLightNode();
        void compute() override;
    };

    /**
     * @brief A node that visualizes a value on a dial / gauge. Inputs Value/Min/Max; renders a painted
     *        arc-gauge with a needle at the normalized position. The displayed value is tagged on the
     *        widget (krs_gauge_value / krs_gauge_norm) so it is gate-observable (GATE VIS).
     */
    class DialGaugeNode : public Node {
    public:
        QWidget* createCustomWidget() override;
        DialGaugeNode();
        void compute() override;
        bool refreshUi() override;   // push m_norm/m_value to the gauge IF changed (capped UI rate)
    private:
        QPointer<QWidget> m_gauge;   // the painted GaugeWidget (owned by the node body once mounted)
        double m_norm = 0.0, m_value = 0.0;          // set by compute()
        double m_lastNorm = 0.0, m_lastValue = 0.0;  // last value pushed to the widget
        bool m_have = false, m_pushed = false;       // m_pushed: a real first-push flag (no value sentinel)
    };

    /**
     * @brief A numeric readout styled as a 7-segment LCD (QLCDNumber). Inputs: Value (the number to show),
     *        Digits (int, segment count), Decimals (int, fractional places). Outputs the formatted text on
     *        "Display" so the shown value is gate-observable; the LCD shows the same formatted value.
     */
    class NumericReadoutNode : public Node {
    public:
        QWidget* createCustomWidget() override;
        NumericReadoutNode();
        void compute() override;
        bool refreshUi() override;   // push m_text/m_digits to the LCD IF changed (capped UI rate)
    private:
        QPointer<QLCDNumber> m_lcd;
        std::string m_text; int m_digits = 6; bool m_have = false, m_pushed = false;   // set by compute()
        std::string m_lastText; int m_lastDigits = -1;               // last pushed to the LCD
    };

    /**
     * @brief A node that plots a value over time.
     */
    class ValuePlotterNode : public Node {
    public:
        QWidget* createCustomWidget() override;
        ValuePlotterNode();
        void compute() override;
    private:
        std::deque<std::pair<float, float>> m_history; // Stores (time, value)
        const size_t MAX_HISTORY = 200;
    };


    // --- Monitoring & Logging Nodes ---

    /**
     * @brief A passthrough node that logs errors based on a configurable condition.
     */
    class DataMonitorNode : public Node {
    public:
        QWidget* createCustomWidget() override;
        // Configurable properties for the monitor instance.
        std::function<bool(float)> errorCondition;
        std::string errorMessage = "Value out of bounds!";
        ErrorLogEntry::Severity errorSeverity = ErrorLogEntry::Severity::Error;

        DataMonitorNode();
        void compute() override;
    };

} // namespace NodeLibrary