#pragma once
// YcbCatalog.hpp -- the curated YCB object library (Yale-CMU-Berkeley object set; free research use). 20
// objects spanning boxes / cylinders / cans / bottles / concavities (bowl,mug,cup,pitcher) / tools / spheres
// / thin items. anchorLongest{Min,Max} are published-dimension anchors on the AABB's LONGEST axis for objects
// whose real size I can pin confidently (orientation-robust ones); 0 means "use only the universal band".
#include <string>
#include <vector>

namespace krs::grasp {

struct YcbObject {
    std::string id;          // e.g. "025_mug"
    std::string category;    // box / cylinder / can / bottle / concave / tool / sphere / thin
    bool        concavity;   // has a grasp-relevant cavity (bowl/mug/cup/pitcher) -> used by GATE COACD
    double      anchorLongestMin;  // tight published-dimension anchor on the AABB longest axis (m); 0 = none
    double      anchorLongestMax;
    std::string meshPath() const;  // resolved absolute path to the geometry (.ply)
    std::string coacdPath() const; // resolved absolute path to the cooked CoACD convex parts (.bin)
};

// The library. Mesh dir defaults to the repo assets/ycb, overridable via KRS_YCB_DIR.
const std::vector<YcbObject>& ycbCatalog();

// True when the YCB mesh pack is actually present on disk (the ~117 MB download is optional --
// .gitignore excludes assets/ycb; fetch via scripts/download_ycb.sh). Checks the first object's mesh.
bool ycbAssetsAvailable();

// Gate guard: if the YCB pack is absent, print a SKIP line for gateName, mark the bench outcome as
// SKIP (krs::gate::skip()) and return true. A grasp gate calls `if (ycbSkipIfAbsent("...")) return true;`
// so a clean checkout reports SKIP instead of a hard FAIL on missing optional assets.
bool ycbSkipIfAbsent(const char* gateName);

// True when the offline-cooked CoACD colliders (assets/ycb/<id>/coacd.bin, generated by scripts/gen_coacd.py)
// are present. Distinct from the meshes -- a representative object's coacd.bin is checked.
bool ycbCoacdAvailable();

// Gate guard for the gates that REQUIRE cooked CoACD colliders to discriminate (COACD-REAL, HEURISTIC-V2):
// if the colliders are absent, SKIP rather than hard-FAIL (run scripts/gen_coacd.py to cook them).
bool coacdSkipIfAbsent(const char* gateName);

// universal manipulation-object scale band (the AABB longest axis must lie inside this, in meters).
constexpr double kScaleBandMin = 0.02;   // 2 cm
constexpr double kScaleBandMax = 0.40;   // 40 cm

} // namespace krs::grasp
