#ifndef PROPERTIESPANEL_H
#define PROPERTIESPANEL_H

#include <QWidget>

// Forward declaration for the UI class generated by Qt Designer
namespace Ui {
class PropertiesPanel;
}

class PropertiesPanel : public QWidget
{
    Q_OBJECT

public:
    explicit PropertiesPanel(QWidget *parent = nullptr);
    ~PropertiesPanel();

private:
    Ui::PropertiesPanel *ui; // Pointer to the UI class
};

#endif // PROPERTIESPANEL_H
