#include "StaticToolbar.hpp"
#include "ui_static_toolbar.h" // Include the header generated by uic

StaticToolbar::StaticToolbar(QWidget* parent) :
    QWidget(parent),
    ui(new Ui::toolbarContainer) // Instantiate the UI class
{
    ui->setupUi(this); // Set up the UI onto this widget instance

    // You can connect signals/slots for your toolbar buttons here if needed
    // For example:
    // connect(ui->new_project_button, &QToolButton::clicked, this, &YourSlotClass::onNewProjectClicked);
}

StaticToolbar::~StaticToolbar()
{
    delete ui;
}