#pragma once

#include <QWidget>
#include "ViewportManagerPopup.hpp"
#include "MenuFactory.hpp"
#include <QToolButton>
#include <QHash>
#include "IMenu.hpp"

// Forward declaration for the UI class generated by uic
namespace Ui {
    class toolbarContainer;
}

class StaticToolbar : public QWidget
{
    Q_OBJECT

public:
    explicit StaticToolbar(QWidget* parent = nullptr);
    ~StaticToolbar() override;

    ViewportManagerPopup* viewportManagerPopup() const { return m_viewportManagerPopup; }

    void uncheckButtonForMenu(MenuType type);

    /// Reflect the simulation state on the play/pause button (checked = playing).
    void setSimulationPlaying(bool playing);

    /// Generic (non-IMenu) dockable-panel buttons: keep a button's checked state in sync
    /// with its dock visibility (called by MainWindow when a dock is shown/closed).
    void setPanelButtonChecked(const QString& panelId, bool checked);
    /// Headless self-test: programmatically click a panel button (toggles + emits).
    void selfTestClickPanel(const QString& panelId);

    /// ACTION-BUS accessors: MainWindow attaches dropdown QMenus to specific ribbon buttons
    /// (setMenu + InstantPopup) and reads the shared combos. Returns nullptr/empty when absent.
    QToolButton* buttonById(const QString& objectName) const;
    class QComboBox* comboById(const QString& objectName) const;
    QString lengthUnit() const;   // current selection of units_length_input ("m","cm","mm","in")
    QString angleUnit() const;    // current selection of units_angle_input ("deg","rad")
    // StaticToolbar.hpp
public slots:
    void checkButtonForMenu(MenuType type);

protected:
    bool eventFilter(QObject* obj, QEvent* event) override; // theme swatch clicks

signals:
    void loadRobotClicked();
    void viewportManagerClicked(QToolButton* button);

    void flowMenuToggled(bool checked);
    void realSenseMenuToggled(bool checked);
    void databaseMenuToggled(bool checked);
	void gridMenuToggled(bool checked);
    void objectPropertiesMenuToggled(bool checked);

    /// Generic toggle for the always-docked panels (Physics, Lighting, Textures, Outliner,
    /// Robot Builder, Assets, Diagnostics, Fluid, Gas, Robot View, Node Editor). panelId is
    /// the dock title; MainWindow looks it up in m_panelDocks and calls toggleView.
    void panelToggled(const QString& panelId, bool checked);
    /// Theme selector (e.g. "dark" / "light").
    void themeSelected(const QString& theme);

    // Simulation lifecycle (play/pause is one checkable button)
    void simulationPlayPauseToggled(bool play);
    void simulationResetClicked();
    void simulationStepClicked();
    /// Simulation speed slider (0.1x .. 4.0x, label kept in sync internally).
    void simSpeedChanged(double factor);

    /// THE GENERIC ACTION BUS: every ribbon button without a dedicated signal emits its
    /// objectName here; MainWindow dispatches. A new .ui button is wire-able the moment it
    /// has a name -- no new signal needed.
    void toolbarAction(const QString& actionId);

private:
    Ui::toolbarContainer* ui; // Pointer to the generated UI class
    ViewportManagerPopup* m_viewportManagerPopup;
    // dock title -> its toggle button(s). MULTI: a dock may have both a dedicated ribbon button
    // AND a Panels-tab button (Assets/Outliner/Diagnostics) -- checked-state sync updates all.
    QMultiHash<QString, QToolButton*> m_panelButtons;
    QHash<QObject*, QString>          m_swatchThemes; // theme swatch frame -> theme id
};