#pragma once

#include <QWidget>
#include "ViewportManagerPopup.hpp"

// Forward declaration for the UI class generated by uic
namespace Ui {
    class toolbarContainer;
}

class StaticToolbar : public QWidget
{
    Q_OBJECT

public:
    explicit StaticToolbar(QWidget* parent = nullptr);
    ~StaticToolbar() override;

    ViewportManagerPopup* viewportManagerPopup() const { return m_viewportManagerPopup; }

signals:
    void loadRobotClicked();
    void viewportManagerClicked(QToolButton* button);

    void flowMenuToggled(bool checked);
    void realSenseMenuToggled(bool checked);
    void databaseMenuToggled(bool checked);

private:
    Ui::toolbarContainer* ui; // Pointer to the generated UI class
    ViewportManagerPopup* m_viewportManagerPopup;
};