#pragma once

#include <QWidget>

// Forward declaration for the UI class generated by uic
namespace Ui {
    class toolbarContainer;
}

class StaticToolbar : public QWidget
{
    Q_OBJECT

public:
    explicit StaticToolbar(QWidget* parent = nullptr);
    ~StaticToolbar();

signals:
    void loadRobotClicked();
    void viewportManagerClicked();

private:
    Ui::toolbarContainer* ui; // Pointer to the generated UI class
};