name: macOS Build & Package

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  mac:
    runs-on: macos-14 # Apple-Silicon runner

    # ──────────────── global env ────────────────
    env:
      BUILD_TYPE: Release
      QT_VERSION: 6.9.0
      # Use the same simple file-based cache as the Windows workflow for consistency and reliability.
      VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg-cache,readwrite"

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Cache vcpkg binaries
      # This single step now handles the compiled dependency cache.
      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg-cache
          key: vcpkg-bins-macos-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: vcpkg-bins-macos-

      # 3. Cache the project's own build directory
      # Added this step for faster subsequent builds of your own code.
      - name: Cache CMake build directory
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build
          key: cmake-build-macos-${{ hashFiles('**/CMakeLists.txt', 'src/**', 'include/**') }}
          restore-keys: cmake-build-macos-

      # 4. Dependencies
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: c6f09fc73ebfbfddd769f8fac9f33f95304c77e5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          # Corrected architecture for Apple Silicon runners to what aqtinstall expects.
          arch: "arm64"
          # Corrected module names for aqtinstall. qtbase is installed by default.
          modules: "shadertools svg"

      # 5. Configure & build
      - name: Configure
        run: |
          cmake -B build -S . \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      # 6. Bundle & ad-hoc sign
      - name: macdeployqt (plus ad-hoc codesign)
        run: |
          # Corrected the path: The .app bundle is typically in the root of the build directory.
          macdeployqt build/RoboticsSoftware.app -always-overwrite -verbose=2
          # ad-hoc sign so Gatekeeper is satisfied when the DMG is downloaded
          codesign --force --deep --sign - build/RoboticsSoftware.app

      # 7. Create DMG & upload
      - name: Create DMG
        run: packaging/create-dmg.sh

      - uses: actions/upload-artifact@v4
        with:
          name: KRStudio-mac
          path: KRStudio-mac.dmg
