name: ci-mac

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-osx
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: lukka/run-vcpkg@v11
        with:
          setupOnly: true

      - name: Configure (Release)
        run: cmake --preset macos-ninja-release

      - name: Build
        run: cmake --build --preset mac-release --parallel

      - name: Try macdeployqt (optional)
        shell: bash
        run: |
          APP_BUNDLE="build/macos-release/RoboticsSoftware.app"
          if [ -d "$APP_BUNDLE" ]; then
            TOOLS_ARM="$VCPKG_ROOT/installed/arm64-osx/tools/Qt6/bin/macdeployqt"
            TOOLS_X64="$VCPKG_ROOT/installed/x64-osx/tools/Qt6/bin/macdeployqt"
            if [ -x "$TOOLS_ARM" ]; then
              "$TOOLS_ARM" "$APP_BUNDLE" -verbose=2 || true
            elif [ -x "$TOOLS_X64" ]; then
              "$TOOLS_X64" "$APP_BUNDLE" -verbose=2 || true
            else
              echo "macdeployqt not found in vcpkg tools; skipping."
            fi
          else
            echo "No .app bundle found; skipping deploy."
          fi

      - name: Archive
        run: |
          cd build/macos-release
          /usr/bin/zip -r KRStudio-macOS.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: KRStudio-macOS
          path: build/macos-release/KRStudio-macOS.zip
