name: Windows Build & Package

on:
  push: { branches: [main] }
  pull_request:
  workflow_dispatch:
  release: { types: [created] }

jobs:
  win:
    runs-on: windows-latest
    env:
      BUILD_TYPE: Release
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Cache CMake build directory
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt', 'src/**', 'include/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.BUILD_TYPE }}-
            
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{github.workspace}}/vcpkg
          vcpkgGitCommitId: c6f09fc73ebfbfddd769f8fac9f33f95304c77e5
          vcpkg-cache-key: ${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.0
          host: windows
          dir: ${{runner.temp}}/Qt
          
      - name: Configure
        run: >
          cmake -B build -S .
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake
          
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel
        
      - name: Bundle runtime libs
        shell: cmd
        run: |
          set PATH=%PATH%;%QT_BIN_DIR%
          windeployqt --release build\%BUILD_TYPE%\RoboticsSoftware.exe
          copy README.md build\%BUILD_TYPE%
      
      - name: Setup Inno Setup
        run: |
          $inno_url = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
          $inno_installer = "${{ runner.temp }}\innosetup-installer.exe"
          Write-Host "Downloading Inno Setup..."
          Invoke-WebRequest -Uri $inno_url -OutFile $inno_installer
          
          Write-Host "Installing Inno Setup..."
          Start-Process -FilePath $inno_installer -ArgumentList "/SILENT /NOCANCEL /SUPPRESSMSGBOXES" -Wait
          
          $inno_path = "C:\Program Files (x86)\Inno Setup 6"
          echo $inno_path >> $env:GITHUB_PATH
          
      - name: Build installer
        run: iscc packaging/InnoSetup.iss
        
      - uses: actions/upload-artifact@v4
        with:
          name: KRStudio-win64
          path: packaging/dist/installer/*.exe
