name: ci-win

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: lukka/run-vcpkg@v11
        with:
          setupOnly: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (Release)
        run: cmake --preset windows-ninja-release

      - name: Build
        run: cmake --build --preset release --parallel

      - name: Archive
        run: |
          cd build/release
          powershell -Command "Compress-Archive -Path * -DestinationPath KRStudio-Release.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: KRStudio-Windows
          path: build/release/KRStudio-Release.zip
